ЗАКАЗ SPACE SEC от ilja🤠
AdventureTimeSS14/space_station pull request #755
Opened 2024-06-16 19:47 UTC by Lonkuk

## Описание PR

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Добавлены прототипы по заказу SPACE SEC
![Screenshot_1107](https://github.com/xtray85/space_station/assets/115577759/5ad29c6c-0186-4b03-b185-713537d24427)

2024-06-16 20:46 UTC, Schrodinger71 requested changes
Ругается мол нет такого

![image](https://github.com/xtray85/space_station/assets/132720404/094d8f67-1ab4-45dc-8032-fbdc38a3ca58)

2024-06-16 20:59 UTC, modern-nm commented
> ## Описание PR
> **Проверки**
> 
> * [x]  PR полностью завершён и мне не нужна помощь чтобы его закончить.
> * [x]  Я внимательно просмотрел все свои изменения и багов в них не нашёл.
> * [x]  Я запускал локальный сервер со своими изменениями и всё протестировал.
> * [x]  Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.
> 
> **Изменения**
> 
> 🆑
> 
> * add: Добавлены прототипы по заказу SPACE SEC
>   ![Screenshot_1107](https://private-user-images.githubusercontent.com/115577759/340130898-5ad29c6c-0186-4b03-b185-713537d24427.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1NzE3NjYsIm5iZiI6MTcxODU3MTQ2NiwicGF0aCI6Ii8xMTU1Nzc3NTkvMzQwMTMwODk4LTVhZDI5YzZjLTAxODYtNGIwMy1iMTg1LTcxMzUzN2QyNDQyNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNlQyMDU3NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMDk1ZmQ0ODc4ZTdkY2EwNTE3YmZmM2VmM2U3MmI1ZWVkZmRiNjk0YzM1YjU3ZWRlODMwODZjYThlNmU2NDViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TjpdLm-8iXtpCdyR35BLQxfADHqL-95vIHKpjLqxomU)
блок с изменениями, начинающийся с 🆑, предназначен для парсера и не должен содержать скриншоты.

2024-06-17 11:54 UTC, 1Stepka1 commented
Если space sec humanoid то какого хрена они в отдельном файле? Resources/Prototypes/ADT/Entities/Mobs/player/space_sec_humanoid.yml перенести в Resources/Prototypes/ADT/Entities/Mobs/player/humanoid.yml
Resources/Prototypes/ADT/Entities/Objects/Misc/space_sec_id.yml это не уникальные айди, перенести в Resources/Prototypes/ADT/Entities/Objects/Misc/identification_cards.yml
Resources/Prototypes/ADT/StatusEffects/space_sec_job.yml это не уникальные иконки, перенести в Resources/Prototypes/ADT/StatusEffects/job.yml
Так же есть придирки к названию папок и файлов,к примеру Resources/Prototypes/ADT/StartingGear/SpaceSec/SpaceSecCadet.yml это уже в папке SpaceSec,зачем повторять ещё раз?

2024-06-21 20:37 UTC, Lonkuk commented
Вроде всё поправил

2024-06-27 18:39 UTC, Schrodinger71 commented
@Lonkuk Теперь такая ошибка

![image](https://github.com/xtray85/space_station/assets/132720404/5fc6b830-77d1-4142-8f52-c8998ded2b32)

2024-07-01 14:09 UTC, Schrodinger71 commented
Даже не знаю, ты создал отдельную папку в ADT под SpaceSec что-то это не очень хорошо. Разниться с визардовской структурой
И меняешь официальные файлы без комментирования их, что это наши `# ADT tweak` изменения

Решай или ты сейчас тут починишь чтобы легче было при переносе, или замерджим, и переносить уже будет немного трудозатратнее в новую репу


![image](https://github.com/AdventureTimeSS14/space_station/assets/132720404/bbc335aa-993b-408b-b5a6-6ec1e8c327e9)

2024-07-03 06:56 UTC, Schrodinger71 approved these changes

2024-07-03 07:02 UTC, merged